# Generated by Django 5.2.1 on 2025-12-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_post_alter_notification_related_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_post',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('join_request', 'Заявка на участие'), ('request_approved', 'Заявка одобрена'), ('request_rejected', 'Заявка отклонена'), ('new_message', 'Новое сообщение'), ('system', 'Системное уведомление'), ('event_completed', 'Мероприятие завершено')], default='system', max_length=20),
        ),
    ]
