# Generated by Django 5.2.1 on 2025-11-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='type',
        ),
        migrations.AddField(
            model_name='posts',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='posts',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
