# Generated by Django 5.2.1 on 2025-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_comment_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='posts',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('prefer-not-to-say', 'Предпочитаю не говорить')], max_length=20, null=True),
        ),
    ]
