# Generated by Django 5.2.1 on 2025-11-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_error',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
