# Generated by Django 5.2.1 on 2025-11-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_notification_postparticipant_postrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
